/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import clases.Alquiler;
import clases.Producto;
import clases.Sistema;
import clases.Usuario;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gerar
 */
public class FrmDevolucion extends javax.swing.JFrame {

    private Usuario usuarioLogueado;
    private Sistema sistema;
    private Alquiler alquilerSeleccionado = null;

    /**
     * Creates new form FrmDevolucion
     */
    public FrmDevolucion(Usuario usuario, Sistema sistema) {
        initComponents();
        this.usuarioLogueado = usuario;
        this.sistema = sistema;
        this.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        this.setTitle("Gestión de Devoluciones");
        this.setLocationRelativeTo(null);

        cargarListaAlquileres();
        btnDevolver.setEnabled(false);

        tblAlquileres.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila = tblAlquileres.getSelectedRow();
                if (fila != -1) {
                    int idAlquiler = (int) tblAlquileres.getValueAt(fila, 0);
                    alquilerSeleccionado = sistema.buscarAlquilerPorID(idAlquiler);
                    cargarDetalleAlquiler(alquilerSeleccionado);
                }
            }
        });
    }

    private void cargarListaAlquileres() {
        DefaultTableModel modelo = new DefaultTableModel(new String[]{"ID", "Cliente (DNI)", "Nombre", "Total (S/)"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Tabla no editable
            }
        };

        for (Alquiler alq : sistema.getAlquileres()) {
            modelo.addRow(new Object[]{
                alq.getIdAlquiler(),
                alq.getCliente().getDni(),
                alq.getCliente().getNombre() + " " + alq.getCliente().getApellido(),
                String.format("%.2f", alq.calcularTotal())
            });
        }
        tblAlquileres.setModel(modelo);

        // Si no hay alquileres, limpiar detalles
        if (sistema.getAlquileres().isEmpty()) {
            limpiarDetalles();
        }
    }

    public FrmDevolucion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDevolver = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAlquileres = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDevolver.setText("DEVOLVER");
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblInfo.setText("Cliente");

        tblAlquileres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblAlquileres);

        jScrollPane3.setViewportView(jScrollPane2);

        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDetalle);

        jScrollPane4.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1003, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDevolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(btnSalir)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDevolver)
                    .addComponent(btnSalir)
                    .addComponent(lblInfo))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarDetalles() {
        tblDetalle.setModel(new DefaultTableModel(new String[]{"Producto", "Categoría", "Precio Unit."}, 0));
        lblInfo.setText("Seleccione un alquiler para ver el detalle.");
        btnDevolver.setEnabled(false);
        alquilerSeleccionado = null;
    }

    private void cargarDetalleAlquiler(Alquiler alquiler) {
        if (alquiler == null) {
            return;
        }

        DefaultTableModel modelo = new DefaultTableModel(new String[]{"Producto", "Categoría", "Precio Unit."}, 0);

        for (Producto p : alquiler.getProductos()) {
            modelo.addRow(new Object[]{
                p.getNomProducto(),
                p.getCatProducto(),
                String.format("S/ %.2f", p.getPrecio())
            });
        }
        tblDetalle.setModel(modelo);

        lblInfo.setText("Alquiler ID: " + alquiler.getIdAlquiler() + " - Cliente: " + alquiler.getCliente().getNombre());
        btnDevolver.setEnabled(true);
    }

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        if (alquilerSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un alquiler de la lista superior.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Confirmar devolución del Alquiler ID: " + alquilerSeleccionado.getIdAlquiler() + "?\n"
                + "Los productos volverán al stock.",
                "Procesar Devolución",
                JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            // Lógica central de devolución
            boolean exito = sistema.procesarDevolucion(alquilerSeleccionado);

            if (exito) {
                JOptionPane.showMessageDialog(this, "Devolución exitosa. Stock actualizado.");

                // Refrescar todo
                cargarListaAlquileres();
                limpiarDetalles();

            } else {
                JOptionPane.showMessageDialog(this, "Error al procesar la devolución.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDevolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDevolucion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDevolucion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDevolucion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDevolucion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDevolucion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JTable tblAlquileres;
    private javax.swing.JTable tblDetalle;
    // End of variables declaration//GEN-END:variables

}
