/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import clases.Sistema;
import clases.Usuario;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author DIEGO
 */
public class FrmEncargado extends javax.swing.JFrame {

    /**
     * Creates new form FrmEncargado
     */
    private Usuario usuarioLogueado;
    private Sistema sistema;
    private TableRowSorter<TableModel> sorter;
    private DefaultTableModel modeloTabla;
    public boolean cerrandoSesion = false;

    private void cargarInventarioEnTabla() {

        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

        if (sorter != null) {
            sorter.setRowFilter(null);
        }

        modelo.setRowCount(0);

        for (clases.Producto p : sistema.getInventario().getListaProductos()) {
            Object[] fila = {
                p.getIdProducto(),
                p.getNomProducto(),
                p.getCatProducto(),
                String.format("S/ %.2f", p.getPrecio()),
                p.getStock()
            };
            modelo.addRow(fila);
        }

        if (!txtBuscar.getText().trim().isEmpty()) {
            try {
                sorter.setRowFilter(RowFilter.regexFilter("(?i)" + txtBuscar.getText().trim()));
            } catch (Exception e) {
            }
        }

        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setCellRenderer(new StockAlertRenderer());
        }
    }

    public FrmEncargado(Usuario usuario, Sistema sistema) {
        initComponents();
        this.usuarioLogueado = usuario;
        this.sistema = sistema;

        lblBienvenida.setText("¡Hola, " + usuarioLogueado.getNombre() + "! (" + usuarioLogueado.getRol().getNombreRol() + ")");

        String[] columnas = {"ID", "Nombre", "Categoría", "Precio", "Stock"};
        modeloTabla = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTable1.setModel(modeloTabla);
        sorter = new TableRowSorter<>(modeloTabla);
        jTable1.setRowSorter(sorter);

        cargarInventarioEnTabla();

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (jTable1.rowAtPoint(evt.getPoint()) == -1) {
                    jTable1.clearSelection();
                }
            }
        });
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1.clearSelection();
            }
        });
    }

    public FrmEncargado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenida = new javax.swing.JLabel();
        lblPNG = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnActPersonal = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnMasStock = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnReporte = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel de Control Encargado");
        setIconImage(getIconImage());
        setResizable(false);

        lblBienvenida.setText("¡Bienvenido, NOMBRE! (ENCARGADO)");

        lblPNG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/encargado.png"))); // NOI18N

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/cerrarsesion.png"))); // NOI18N
        btnSalir.setText("CERRAR SESION");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnActPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/actualizar.png"))); // NOI18N
        btnActPersonal.setText("ACTUALIZAR PERSONAL");
        btnActPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActPersonalActionPerformed(evt);
            }
        });

        btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/actualizar.png"))); // NOI18N
        btnInventario.setText("ACTUALIZAR INVENTARIO");
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/logohd.jpg"))); // NOI18N

        btnMasStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/agregar.png"))); // NOI18N
        btnMasStock.setText("AÑADIR STOCK");
        btnMasStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasStockActionPerformed(evt);
            }
        });

        jLabel2.setText("Buscar Producto :");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        btnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/anotar.png"))); // NOI18N
        btnReporte.setText("REPORTE");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        btnHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/anotar.png"))); // NOI18N
        btnHistorial.setText("HISTORIAL");
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(lblPNG)))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnInventario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReporte, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMasStock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnActPersonal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHistorial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBienvenida)
                        .addGap(18, 18, 18)
                        .addComponent(lblPNG))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnActPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMasStock, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );

        setSize(new java.awt.Dimension(826, 840));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int opcion = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que deseas cerrar sesión?",
                "Confirmar cierre de sesión",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE
        );

        if (opcion == javax.swing.JOptionPane.YES_OPTION) {
            // AVISAMOS QUE ES UN CIERRE DE SESIÓN, NO UN REGRESO
            this.cerrandoSesion = true;

            sistema.guardarDatos();
            dispose(); // Esto disparará el evento de cierre

            FrmLogin login = new FrmLogin(this.sistema);
            login.setVisible(true);
        }

    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnActPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActPersonalActionPerformed
        FrmRegistrar frmReg = new FrmRegistrar(this.sistema, null);

        frmReg.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                actualizarListaUsuarios();
            }
        });

        frmReg.setVisible(true);
    }//GEN-LAST:event_btnActPersonalActionPerformed

    private void actualizarListaUsuarios() {
        javax.swing.DefaultListModel<String> listModel = new javax.swing.DefaultListModel<>();
        listModel.addElement("--- Lista de Personal Registrado ---");

        if (sistema != null && sistema.getUsuarios() != null) {
            for (clases.Usuario u : sistema.getUsuarios()) {
                listModel.addElement(u.getDni() + " - " + u.getNombre() + " (" + u.getRol().getNombreRol() + ")");
            }
        }
    }


    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed

        int fila = jTable1.getSelectedRow();
        jTable1.clearSelection();

        clases.Producto productoAEditar = null;
        if (fila != -1) {
            try {
                int id = Integer.parseInt(jTable1.getValueAt(fila, 0).toString());
                productoAEditar = sistema.getInventario().buscarProducto(id);
            } catch (Exception e) {
            }
        }

        FrmProducto frm = new FrmProducto(sistema, productoAEditar, null);

        frm.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                cargarInventarioEnTabla();
            }
        });

        frm.setVisible(true);

    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnMasStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasStockActionPerformed

        int fila = jTable1.getSelectedRow();
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un producto de la tabla.", "Selección Requerida", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idProducto = (int) jTable1.getValueAt(fila, 0);
        clases.Producto producto = sistema.getInventario().buscarProducto(idProducto);

        if (producto != null) {

            String input = javax.swing.JOptionPane.showInputDialog(this,
                    "Stock actual: " + producto.getStock() + "\nIngrese cantidad a agregar:",
                    "Reabastecer Stock",
                    javax.swing.JOptionPane.QUESTION_MESSAGE);

            if (input != null && !input.isEmpty()) {
                try {
                    int cantidad = Integer.parseInt(input);

                    if (cantidad > 0) {

                        producto.aumentarStock(cantidad);
                        sistema.guardarDatos();

                        cargarInventarioEnTabla();
                        javax.swing.JOptionPane.showMessageDialog(this, "Stock actualizado. Nuevo total: " + producto.getStock());
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor a 0.");
                    }
                } catch (NumberFormatException e) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un número válido.");
                }
            }
        }
    }//GEN-LAST:event_btnMasStockActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        String textoBusqueda = txtBuscar.getText().trim();
        if (textoBusqueda.length() == 0) {

            sorter.setRowFilter(null);
        } else {

            try {
                sorter.setRowFilter(RowFilter.regexFilter("(?i)" + textoBusqueda));
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        try {

            File carpeta = new File("Reportes");
            if (!carpeta.exists()) {
                carpeta.mkdir();
            }

            String nombreArchivo = "Reporte_Inventario_" + new SimpleDateFormat("yyyyMMdd_HHmm").format(new Date()) + ".pdf";
            File archivo = new File(carpeta, nombreArchivo);

            sistema.generarPDFInventario(archivo, this.usuarioLogueado);

            if (Desktop.isDesktopSupported() && archivo.exists()) {
                Desktop.getDesktop().open(archivo);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Reporte guardado en: " + archivo.getAbsolutePath());
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al generar reporte: " + e.getMessage());
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        int fila = jTable1.getSelectedRow();
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Por favor, selecciona un producto de la tabla para ver sus movimientos.", 
                    "Selección Requerida", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idProd = Integer.parseInt(jTable1.getValueAt(fila, 0).toString());
        String nombreProd = jTable1.getValueAt(fila, 1).toString();

        StringBuilder historial = new StringBuilder();
        historial.append("HISTORIAL DE MOVIMIENTOS: ").append(nombreProd).append("\n\n");

        boolean tuvoMovimientos = false;

        for (clases.Alquiler alq : sistema.getAlquileres()) {
            for (clases.Producto p : alq.getProductos()) {

                if (p.getIdProducto() == idProd) {
                    historial.append("-> Alquiler N° ").append(alq.getIdAlquiler())
                            .append(" | Cliente: ").append(alq.getCliente().getNombre())
                            .append(" | Días: ").append(alq.getDias())
                            .append("\n");
                    tuvoMovimientos = true;
                }
            }
        }

        if (!tuvoMovimientos) {
            historial.append("Este producto no registra salidas ni alquileres hasta el momento.");
        }

        javax.swing.JTextArea area = new javax.swing.JTextArea(historial.toString());
        area.setEditable(false);
        area.setRows(10);
        area.setColumns(40);
        javax.swing.JOptionPane.showMessageDialog(this, new javax.swing.JScrollPane(area), "Kardex del Producto", javax.swing.JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_btnHistorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEncargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEncargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEncargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEncargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEncargado().setVisible(true);
            }
        });
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("media/logofinal.png"));

        return retValue;
    }

    private String recortar(String texto, int max) {
        if (texto == null) {
            return "";
        }
        if (texto.length() <= max) {
            return texto;
        }
        return texto.substring(0, max - 3) + "...";
    }

    class StockAlertRenderer extends javax.swing.table.DefaultTableCellRenderer {

        @Override
        public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            java.awt.Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

            int stock = Integer.parseInt(table.getValueAt(row, 4).toString());

            if (stock < 5) {
                c.setBackground(new java.awt.Color(255, 204, 204));
                c.setForeground(java.awt.Color.RED);
            } else {
                c.setBackground(java.awt.Color.WHITE);
                c.setForeground(java.awt.Color.BLACK);
            }
            if (isSelected) {
                c.setBackground(table.getSelectionBackground());
                c.setForeground(table.getSelectionForeground());
            }

            return c;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActPersonal;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnMasStock;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblPNG;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
