/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import clases.Sistema;
import clases.Usuario;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.awt.Desktop;
import java.io.File;
import java.util.List;

/**
 *
 * @author DIEGO
 */
public class FrmInvitado extends javax.swing.JFrame {

    /**
     * Creates new form FrmInvitado
     */
    private Usuario usuarioLogueado;
    private Sistema sistema;

    private String obtenerUltimoEstado() {
        List<String> historial = usuarioLogueado.getAsistencia();
        if (historial.isEmpty()) {
            return "NINGUNO";
        }
        // Obtenemos el último registro de la lista
        String ultimo = historial.get(historial.size() - 1);

        if (ultimo.startsWith("ENTRADA")) {
            return "ENTRADA";
        }
        if (ultimo.startsWith("SALIDA")) {
            return "SALIDA";
        }
        return "DESCONOCIDO";
    }

    private void cargarInfoEmpresa() {
        txaInfoEmpresa.setEditable(false);
        txaInfoEmpresa.setText("""
            ============================================================
                            GUÍA DE PERSONAL DE APOYO (TEMPORAL)
            ============================================================
            
            UBICACIÓN Y HORARIO:
               - Base Operativa: Villa El Salvador, Mz G Lote 16
               - Horario de Turno: 8:00 AM - 5:00 PM (Revisar con Supervisor)
            
            CANALES DE COMUNICACIÓN:
               - Encargado de Almacén:  951 638 873 (Coordinación diaria)
               - Administración:        (01) 555-1234
               - Emergencias:           Reportar inmediato a Caseta de Seguridad
            
            TUS RESPONSABILIDADES PRINCIPALES:
               1. Apoyo en la carga y descarga de estructuras metálicas.
               2. Limpieza y conteo de sillas/mesas devueltas de alquiler.
               3. Uso OBLIGATORIO de casco y botas (EPP) en zona de carga.
               4. Reportar material dañado al Encargado de turno.
            
            IMPORTANTE: 
               Recuerda marcar tu asistencia en la entrada y salida para el
               pago de tus horas.
            """);
        txaInfoEmpresa.setCaretPosition(0);
    }

    public FrmInvitado(Usuario usuario, Sistema sistema) {
        initComponents();
        this.usuarioLogueado = usuario;
        this.sistema = sistema;

        lblBienvenida.setText("¡Hola, " + usuarioLogueado.getNombre() + "! (PERSONAL TEMPORAL)");

        cargarInfoEmpresa();

        for (java.awt.event.ActionListener al : btnSalir.getActionListeners()) {
            btnSalir.removeActionListener(al);
        }

        btnSalir.addActionListener(e -> {
            int opcion = javax.swing.JOptionPane.showConfirmDialog(
                    this,
                    "¿Seguro que deseas cerrar sesión?",
                    "Confirmar cierre de sesión",
                    javax.swing.JOptionPane.YES_NO_OPTION,
                    javax.swing.JOptionPane.QUESTION_MESSAGE
            );

            if (opcion == javax.swing.JOptionPane.YES_OPTION) {
                sistema.guardarDatos();
                dispose();
                FrmLogin login = new FrmLogin(this.sistema);
                login.setVisible(true);
            }
        });
    }

    public FrmInvitado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenida = new javax.swing.JLabel();
        lblPng = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaInfoEmpresa = new javax.swing.JTextArea();
        btnEntrada = new javax.swing.JButton();
        btnSalida = new javax.swing.JButton();
        btnReporteAsistencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel de Control Invitado");
        setIconImage(getIconImage());
        setResizable(false);

        lblBienvenida.setText("¡Hola, NOMBRE! (INVITADO)");

        lblPng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/invitados.png"))); // NOI18N

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/cerrarsesion.png"))); // NOI18N
        btnSalir.setText("CERRAR SESION");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/logohd.jpg"))); // NOI18N

        txaInfoEmpresa.setColumns(20);
        txaInfoEmpresa.setRows(5);
        jScrollPane2.setViewportView(txaInfoEmpresa);

        btnEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/anotar.png"))); // NOI18N
        btnEntrada.setText("REGISTRAR ENTRADA");
        btnEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaActionPerformed(evt);
            }
        });

        btnSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/anotar.png"))); // NOI18N
        btnSalida.setText("REGISTRAR SALIDA");
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });

        btnReporteAsistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/anotar.png"))); // NOI18N
        btnReporteAsistencia.setText("REPORTE DE ASISTENCIA");
        btnReporteAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteAsistenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnReporteAsistencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBienvenida, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblPng)
                                .addGap(30, 30, 30)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBienvenida)
                        .addGap(18, 18, 18)
                        .addComponent(lblPng)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReporteAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(835, 681));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaActionPerformed
        String estado = obtenerUltimoEstado();

        if (estado.equals("ENTRADA")) {
            JOptionPane.showMessageDialog(this,
                    "Ya registraste tu ingreso. Debes marcar SALIDA antes.",
                    "Acción Bloqueada", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (JOptionPane.showConfirmDialog(this, "¿Registrar ingreso ahora?", "Confirmar Entrada", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            sistema.registrarAsistencia(usuarioLogueado, "ENTRADA (Invitado)");
            sistema.guardarDatos();

            String hora = new SimpleDateFormat("HH:mm:ss").format(new Date());
            JOptionPane.showMessageDialog(this, "ENTRADA REGISTRADA A LAS " + hora);
        }
    }//GEN-LAST:event_btnEntradaActionPerformed

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
        String estado = obtenerUltimoEstado();

        if (!estado.equals("ENTRADA")) {
            JOptionPane.showMessageDialog(this,
                    "No tienes un ingreso activo. Marca ENTRADA primero.",
                    "Aviso del Sistema", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (JOptionPane.showConfirmDialog(this, "¿Registrar salida ahora?", "Confirmar Salida", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            sistema.registrarAsistencia(usuarioLogueado, "SALIDA (Invitado)");
            sistema.guardarDatos();

            String hora = new SimpleDateFormat("HH:mm:ss").format(new Date());
            JOptionPane.showMessageDialog(this, "SALIDA REGISTRADA A LAS " + hora + "\n¡Gracias por tu apoyo!");
        }
    }//GEN-LAST:event_btnSalidaActionPerformed

    private void btnReporteAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteAsistenciaActionPerformed
        try {
            File carpeta = new File("Invitados");
            if (!carpeta.exists()) {
                carpeta.mkdir();
            }

            String nombreArchivo = "Asistencia_Invitado_" + usuarioLogueado.getDni() + ".pdf";
            File archivoFinal = new File(carpeta, nombreArchivo);

            sistema.generarPDFAsistenciaPersonal(usuarioLogueado, archivoFinal.getAbsolutePath());

            JOptionPane.showMessageDialog(this,
                    "Constancia generada exitosamente en la carpeta 'Invitados'.",
                    "Reporte Generado",
                    JOptionPane.INFORMATION_MESSAGE);

            if (Desktop.isDesktopSupported() && archivoFinal.exists()) {
                Desktop.getDesktop().open(archivoFinal);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                    "Ocurrió un error al generar el PDF:\n" + e.getMessage(), 
                    "Error de Exportación",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnReporteAsistenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInvitado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInvitado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInvitado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInvitado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInvitado().setVisible(true);
            }
        });
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("media/logofinal.png"));

        return retValue;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrada;
    private javax.swing.JButton btnReporteAsistencia;
    private javax.swing.JButton btnSalida;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblPng;
    private javax.swing.JTextArea txaInfoEmpresa;
    // End of variables declaration//GEN-END:variables

}
