/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import clases.Sistema;
import clases.Usuario;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

/**
 *
 * @author gerar
 */
public class FrmLogin extends javax.swing.JFrame {

    private Sistema sistema;
    private boolean mostrarClave = false;

    public FrmLogin() {
        this(new Sistema());
    }

    public FrmLogin(Sistema sistema) {
        initComponents();
        this.sistema = sistema;

        chkInvitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                chkInvitadoActionPerformed(evt);
            }

            private void chkInvitadoActionPerformed(ActionEvent evt) {
                if (chkInvitado.isSelected()) {
                    txtClave.setText("");
                    txtClave.setEnabled(false);
                    btnMostrarClave.setEnabled(false);
                } else {
                    txtClave.setEnabled(true);
                    btnMostrarClave.setEnabled(true);
                }
            }

        });
        this.setDefaultCloseOperation(javax.swing.JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                int opcion = JOptionPane.showConfirmDialog(
                        FrmLogin.this,
                        "¿Seguro que deseas salir de la aplicación?",
                        "Confirmar salida",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE
                );

                if (opcion == JOptionPane.YES_OPTION) {

                    System.out.println("Guardando datos antes de salir...");
                    sistema.guardarDatos();
                    System.exit(0);
                }

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();
        btnMostrarClave = new javax.swing.JButton();
        chkInvitado = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar Sesion");
        setIconImage(getIconImage());
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Nirmala Text", 0, 48)); // NOI18N
        jLabel1.setText("INICIAR SESIÓN");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/dnis.png"))); // NOI18N
        jLabel3.setText("DNI");

        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/login.png"))); // NOI18N
        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/candadologin.png"))); // NOI18N
        jLabel4.setText("CONTRASEÑA");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/persona.png"))); // NOI18N

        jLabel5.setText("En caso de olvidar su contraseña, contacte con un administrador.");

        jLabel6.setText("© 2025 DAL Estructuras S.A.C ");

        btnMostrarClave.setText("MOSTRAR CLAVE");
        btnMostrarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarClaveActionPerformed(evt);
            }
        });

        chkInvitado.setText("Ingresar como Invitado");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/segundologos.png"))); // NOI18N
        jScrollPane1.setViewportView(jLabel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDNI, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtClave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMostrarClave)
                                .addGap(17, 17, 17))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(chkInvitado)
                                .addContainerGap(32, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(185, 185, 185)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel1)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMostrarClave)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chkInvitado)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(0, 128, Short.MAX_VALUE)))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(788, 603));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        String dni = txtDNI.getText().trim();
        String clave = new String(txtClave.getPassword()).trim();

        if (dni.isEmpty() && !chkInvitado.isSelected()) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese su DNI");
            return;
        }

        if (chkInvitado.isSelected()) {
            clave = "";
        } else if (clave.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese su CONTRASEÑA");
            return;
        }

        Usuario usuario = sistema.login(dni, clave);

        if (usuario != null) {
            if (chkInvitado.isSelected() && !"invitado".equalsIgnoreCase(usuario.getRol().getNombreRol())) {
                JOptionPane.showMessageDialog(this, "Este DNI no corresponde a un invitado.");
                return;
            }

            if (!chkInvitado.isSelected() && "invitado".equalsIgnoreCase(usuario.getRol().getNombreRol())) {
                JOptionPane.showMessageDialog(this, "Para ingresar como invitado, marque la casilla correspondiente.");
                return;
            }

            JOptionPane.showMessageDialog(this, "Bienvenido, " + usuario.getNombre()
                    + " (" + usuario.getRol().getNombreRol() + ")");

            String nombreRol = usuario.getRol().getNombreRol();

            switch (nombreRol.toLowerCase()) {
                case "administrador":
                    new FrmAdmin(usuario, sistema).setVisible(true);
                    break;
                case "contadora":
                    new FrmContador(usuario, sistema).setVisible(true);
                    break;
                case "encargado":
                    new FrmEncargado(usuario, sistema).setVisible(true);
                    break;
                case "secretaria":
                    new FrmSecretaria(usuario, sistema).setVisible(true);
                    break;
                case "trabajador":
                    new FrmTrabajador(usuario, sistema).setVisible(true);
                    break;
                case "invitado":
                    if (chkInvitado.isSelected() || sistema.buscarUsuarioPorDNI(dni) != null && "invitado".equalsIgnoreCase(sistema.buscarUsuarioPorDNI(dni).getRol().getNombreRol())) {
                        new FrmInvitado(usuario, sistema).setVisible(true);
                    } else {

                        JOptionPane.showMessageDialog(this, "Error al intentar ingresar como invitado.");
                        return;
                    }
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Rol no reconocido: " + nombreRol);
                    return;
            }
            this.dispose();

        } else {
            if (chkInvitado.isSelected()) {
                JOptionPane.showMessageDialog(this, "DNI de invitado no registrado o incorrecto");
            } else {
                JOptionPane.showMessageDialog(this, "DNI o Contraseña incorrectos");
            }
        }

    }//GEN-LAST:event_btnIngresarActionPerformed


    private void btnMostrarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarClaveActionPerformed
        if (mostrarClave) {
            txtClave.setEchoChar('•');
            btnMostrarClave.setText("MOSTRAR CLAVE");
            mostrarClave = false;
        } else {
            txtClave.setEchoChar((char) 0);
            btnMostrarClave.setText("Ocultar");
            mostrarClave = true;
        }
    }//GEN-LAST:event_btnMostrarClaveActionPerformed

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("media/logofinal.png"));

        return retValue;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        javax.swing.UIManager.put("OptionPane.yesButtonText", "Sí");
        javax.swing.UIManager.put("OptionPane.noButtonText", "No");
        javax.swing.UIManager.put("OptionPane.cancelButtonText", "Cancelar");
        javax.swing.UIManager.put("OptionPane.okButtonText", "Aceptar");
        javax.swing.UIManager.put("OptionPane.titleText", "Mensaje");
        javax.swing.UIManager.put("OptionPane.messageDialogTitle", "Mensaje");

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {

        }

        java.awt.EventQueue.invokeLater(() -> {

            new FrmLogin(new Sistema()).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnMostrarClave;
    private javax.swing.JCheckBox chkInvitado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtDNI;
    // End of variables declaration//GEN-END:variables
}
