/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.text.SimpleDateFormat;
import clases.Alquiler;
import clases.Sistema;
import clases.Usuario;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import javax.swing.DefaultListModel;

/**
 *
 * @author DIEGO
 */
public class FrmSecretaria extends javax.swing.JFrame {

    /**
     * Creates new form FrmSecretaria
     */
    private Usuario usuarioLogueado;
    private Sistema sistema;
    private DefaultListModel<String> modeloLista;

    public FrmSecretaria(Usuario usuario, Sistema sistema) {
        initComponents();
        this.usuarioLogueado = usuario;
        this.sistema = sistema;

        lblBienvenida.setText("¡Hola, " + usuarioLogueado.getNombre() + "! (" + usuarioLogueado.getRol().getNombreRol() + ")");

        modeloLista = new DefaultListModel<>();
        jList1.setModel(modeloLista);
        cargarHistorialAlquileres();

        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowActivated(java.awt.event.WindowEvent e) {
                cargarHistorialAlquileres();
            }
        });

        for (java.awt.event.ActionListener al : btnSalir.getActionListeners()) {
            btnSalir.removeActionListener(al);
        }
        jList1.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                if (evt.getClickCount() == 2) {

                    try {
                        String seleccion = jList1.getSelectedValue();
                        if (seleccion == null || seleccion.startsWith("---")) {
                            return;
                        }

                        String idString = seleccion.split(" | ")[1];
                        int id = Integer.parseInt(idString);

                        Alquiler alquiler = sistema.buscarAlquilerPorID(id);

                        if (alquiler != null) {
                            new FrmRecibo(alquiler).setVisible(true);
                        }
                    } catch (Exception e) {
                        System.err.println("Error al abrir recibo: " + e.getMessage());
                    }
                }
            }
        });

        btnSalir.addActionListener(e -> {
            int opcion = javax.swing.JOptionPane.showConfirmDialog(
                    this,
                    "¿Seguro que deseas cerrar sesión?",
                    "Cerrar Sesión",
                    javax.swing.JOptionPane.YES_NO_OPTION,
                    javax.swing.JOptionPane.QUESTION_MESSAGE
            );

            if (opcion == javax.swing.JOptionPane.YES_OPTION) {
                sistema.guardarDatos();
                dispose();
                FrmLogin login = new FrmLogin(this.sistema);
                login.setVisible(true);
            }
        });
    }

    public FrmSecretaria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenida = new javax.swing.JLabel();
        lblPNG = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnRegistrarSalida = new javax.swing.JButton();
        btnCuentasCompro = new javax.swing.JButton();
        btnRegistrarEntrada = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        btnDevolucion = new javax.swing.JButton();
        btnAlquiler = new javax.swing.JButton();
        btnReporteGlobal = new javax.swing.JButton();
        btnResumenDia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel de Control Secretaria");
        setIconImage(getIconImage());
        setResizable(false);

        lblBienvenida.setText("¡Hola, NOMBRE! (SECRETARIA)");

        lblPNG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/secretaria.png"))); // NOI18N

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/cerrarsesion.png"))); // NOI18N
        btnSalir.setText("CERRAR SESION");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnRegistrarSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/anotar.png"))); // NOI18N
        btnRegistrarSalida.setText("REGISTRAR SALIDA");
        btnRegistrarSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarSalidaActionPerformed(evt);
            }
        });

        btnCuentasCompro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/clavemostrar.png"))); // NOI18N
        btnCuentasCompro.setText("ACTUALIZAR COMPROBANTES");
        btnCuentasCompro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuentasComproActionPerformed(evt);
            }
        });

        btnRegistrarEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/anotar.png"))); // NOI18N
        btnRegistrarEntrada.setText("REGISTRAR ENTRADA");
        btnRegistrarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEntradaActionPerformed(evt);
            }
        });

        jScrollPane1.setToolTipText("c");
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createTitledBorder("Comprobantes"));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setToolTipText("");
        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("HORA: ");

        btnDevolucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/anotar.png"))); // NOI18N
        btnDevolucion.setText("REGISTRAR DEVOLUCIÓN");
        btnDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolucionActionPerformed(evt);
            }
        });

        btnAlquiler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/anotar.png"))); // NOI18N
        btnAlquiler.setText("REGISTRAR ALQUILER");
        btnAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlquilerActionPerformed(evt);
            }
        });

        btnReporteGlobal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/clavemostrar.png"))); // NOI18N
        btnReporteGlobal.setText("REPORTE GLOBAL");
        btnReporteGlobal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteGlobalActionPerformed(evt);
            }
        });

        btnResumenDia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/clavemostrar.png"))); // NOI18N
        btnResumenDia.setText("RESUMEN POR DIA");
        btnResumenDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResumenDiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(48, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBienvenida)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPNG)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(173, 173, 173))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCuentasCompro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDevolucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistrarEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistrarSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlquiler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReporteGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnResumenDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblBienvenida)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblPNG))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCuentasCompro, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnRegistrarEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrarSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnResumenDia, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReporteGlobal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(743, 926));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEntradaActionPerformed
        String dni = javax.swing.JOptionPane.showInputDialog(this, "Ingrese el DNI del personal:", "Registro de Entrada", javax.swing.JOptionPane.QUESTION_MESSAGE);

        if (dni != null && !dni.isEmpty()) {
            clases.Usuario usuario = sistema.buscarUsuarioPorDNI(dni);

            if (usuario != null) {
                sistema.registrarAsistencia(usuario, "ENTRADA (Registrado por Secretaria)");
                javax.swing.JOptionPane.showMessageDialog(this, "Entrada registrada para: " + usuario.getNombre());
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Usuario no encontrado.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnRegistrarEntradaActionPerformed

    private void btnRegistrarSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarSalidaActionPerformed
        String dni = javax.swing.JOptionPane.showInputDialog(this, "Ingrese el DNI del personal para registrar SALIDA:");

        if (dni != null && !dni.isEmpty()) {
            clases.Usuario usuario = sistema.buscarUsuarioPorDNI(dni);

            if (usuario != null) {
                sistema.registrarAsistencia(usuario, "SALIDA (Registrado por Secretaria)");
                javax.swing.JOptionPane.showMessageDialog(this, "Salida registrada para: " + usuario.getNombre());
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Usuario no encontrado.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnRegistrarSalidaActionPerformed

    private void btnCuentasComproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuentasComproActionPerformed
        cargarHistorialAlquileres();
    }//GEN-LAST:event_btnCuentasComproActionPerformed

    private void btnDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolucionActionPerformed

        FrmDevolucion frmDev = new FrmDevolucion(usuarioLogueado, sistema);
        frmDev.setVisible(true);

        frmDev.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {

                btnCuentasComproActionPerformed(null);
            }
        });
    }//GEN-LAST:event_btnDevolucionActionPerformed

    private void btnAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlquilerActionPerformed
        FrmAlquiler frmAlq = new FrmAlquiler(usuarioLogueado, sistema);

        frmAlq.setVisible(true);
    }//GEN-LAST:event_btnAlquilerActionPerformed

    private void btnReporteGlobalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteGlobalActionPerformed
        try {

            File carpeta = new File("Reportes");
            if (!carpeta.exists()) {
                carpeta.mkdir();
            }

            String nombreArchivo = "Reporte_Global_" + System.currentTimeMillis() + ".pdf";
            java.io.File archivo = new java.io.File(carpeta, nombreArchivo);

            sistema.generarPDFGlobal(archivo, usuarioLogueado.getNombre() + " " + usuarioLogueado.getApellido());

            if (java.awt.Desktop.isDesktopSupported()) {
                java.awt.Desktop.getDesktop().open(archivo);
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }

    }//GEN-LAST:event_btnReporteGlobalActionPerformed

    private void btnResumenDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResumenDiaActionPerformed
        try {

            File carpeta = new File("Reportes");
            if (!carpeta.exists()) {
                carpeta.mkdir();
            }

            String nombreArchivo = "Cierre_Caja_" + new SimpleDateFormat("yyyyMMdd").format(new java.util.Date()) + ".pdf";

            String rutaCompleta = new File(carpeta, nombreArchivo).getAbsolutePath();

            sistema.generarPDFCierreCaja(usuarioLogueado, rutaCompleta);

            File archivoGenerado = new File(rutaCompleta);
            if (java.awt.Desktop.isDesktopSupported() && archivoGenerado.exists()) {
                java.awt.Desktop.getDesktop().open(archivoGenerado);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Reporte guardado en Reportes.");
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al generar reporte: " + e.getMessage());
        }

    }//GEN-LAST:event_btnResumenDiaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSecretaria.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSecretaria.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSecretaria.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSecretaria.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSecretaria().setVisible(true);
            }
        });
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("media/logofinal.png"));

        return retValue;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlquiler;
    private javax.swing.JButton btnCuentasCompro;
    private javax.swing.JButton btnDevolucion;
    private javax.swing.JButton btnRegistrarEntrada;
    private javax.swing.JButton btnRegistrarSalida;
    private javax.swing.JButton btnReporteGlobal;
    private javax.swing.JButton btnResumenDia;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblPNG;
    // End of variables declaration//GEN-END:variables

    private String recortar(String texto, int max) {
        if (texto == null) {
            return "";
        }
        return texto.length() > max ? texto.substring(0, max - 3) + "..." : texto;
    }

    private void cargarHistorialAlquileres() {
        modeloLista.clear();
        // Cabecera opcional
        modeloLista.addElement("--- HISTORIAL DE TRANSACCIONES (Doble clic para ver recibo) ---");

        for (Alquiler alq : sistema.getAlquileres()) {
            // Formato: "ID: 1 | Cliente: Juan Perez | Total: S/ 500.00"
            String linea = String.format("ID: %d | Cliente: %s | Total: S/ %.2f",
                    alq.getIdAlquiler(),
                    alq.getCliente().getNombre() + " " + alq.getCliente().getApellido(),
                    alq.calcularTotal()
            );
            modeloLista.addElement(linea);
        }
    }

    private void abrirReciboDeLista(String textoSeleccionado) {
        try {
            // Extraemos el ID de la cadena "ID: 123 | ..."
            String[] partes = textoSeleccionado.split("\\|"); // Separar por la barra vertical
            String parteID = partes[0].replace("ID:", "").trim(); // Quitar texto "ID:"
            int id = Integer.parseInt(parteID);

            // Buscar el alquiler real
            Alquiler alquiler = sistema.buscarAlquilerPorID(id);

            if (alquiler != null) {
                // Abrir la ventana de recibo
                FrmRecibo recibo = new FrmRecibo(alquiler);
                recibo.setVisible(true);
            }
        } catch (Exception e) {
            // Ignorar clics en líneas que no son alquileres (como la cabecera)
        }
    }
}
