/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import clases.Sistema;
import clases.Usuario;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DIEGO
 */
public class FrmTrabajador extends javax.swing.JFrame {

    /**
     * Creates new form FrmTrabajador
     */
    private Usuario usuarioLogueado;
    private Sistema sistema;

    public FrmTrabajador(Usuario usuario, Sistema sistema) {
        initComponents();
        this.usuarioLogueado = usuario;
        this.sistema = sistema;

        lblBienvenida.setText("¡Hola, " + usuarioLogueado.getNombre() + "! (" + usuarioLogueado.getRol().getNombreRol() + ")");

        cargarHistorialAsistencia();

        for (java.awt.event.ActionListener al : btnSalir.getActionListeners()) {
            btnSalir.removeActionListener(al);
        }

        btnSalir.addActionListener(e -> {
            int opcion = javax.swing.JOptionPane.showConfirmDialog(
                    this,
                    "¿Seguro que deseas cerrar sesión?",
                    "Confirmar cierre de sesión",
                    javax.swing.JOptionPane.YES_NO_OPTION,
                    javax.swing.JOptionPane.QUESTION_MESSAGE
            );

            if (opcion == javax.swing.JOptionPane.YES_OPTION) {
                sistema.guardarDatos();
                dispose();
                FrmLogin login = new FrmLogin(this.sistema);
                login.setVisible(true);
            }
        });

        clases.Estilos.estiloVentana(this);

        clases.Estilos.estiloEtiqueta(lblBienvenida, true);

        clases.Estilos.estiloTabla(tblAsistencia, jScrollPane2);

        clases.Estilos.estiloBoton(btnRegistrarEntrada, false);
        clases.Estilos.estiloBoton(btnRegistrarSalida, false);
        clases.Estilos.estiloBoton(btnHonorario, false);
        clases.Estilos.estiloBoton(btnRecibo, false);

        clases.Estilos.estiloBotonDestructivo(btnSalir);

        this.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {

                int opcion = javax.swing.JOptionPane.showConfirmDialog(
                        null,
                        "¿Seguro que deseas salir del sistema?\nSe guardarán los cambios automáticamente.",
                        "Confirmar Salida",
                        javax.swing.JOptionPane.YES_NO_OPTION,
                        javax.swing.JOptionPane.QUESTION_MESSAGE
                );

                if (opcion == javax.swing.JOptionPane.YES_OPTION) {
                    try {
                        if (sistema != null) {
                            sistema.guardarDatos();
                            System.out.println("Datos guardados correctamente al cerrar.");
                        }
                    } catch (Exception ex) {
                        System.err.println("Error al guardar datos al salir: " + ex.getMessage());
                    }

                    System.exit(0);
                }
            }
        });

    }

    public FrmTrabajador() {
        initComponents();
    }

    private void cargarHistorialAsistencia() {
        DefaultTableModel modelo = new DefaultTableModel(new String[]{"Tipo", "Fecha y Hora"}, 0);

        for (String registro : usuarioLogueado.getAsistencia()) {
            String[] partes = registro.split(" - ");
            if (partes.length >= 2) {
                modelo.addRow(new Object[]{partes[0], partes[1]});
            }
        }
        tblAsistencia.setModel(modelo);
    }

    private String obtenerUltimoEstado() {
        List<String> historial = usuarioLogueado.getAsistencia();
        if (historial.isEmpty()) {
            return "NINGUNO";
        }
        String ultimo = historial.get(historial.size() - 1);
        if (ultimo.startsWith("ENTRADA")) {
            return "ENTRADA";
        }
        if (ultimo.startsWith("SALIDA")) {
            return "SALIDA";
        }
        return "DESCONOCIDO";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenida = new javax.swing.JLabel();
        lblPNG = new javax.swing.JLabel();
        btnRegistrarEntrada = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnRecibo = new javax.swing.JButton();
        btnRegistrarSalida = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAsistencia = new javax.swing.JTable();
        btnHonorario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel de Control Trabajador");
        setIconImage(getIconImage());
        setResizable(false);

        lblBienvenida.setText("¡Hola, NOMBRE! (Trabajador)");

        lblPNG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/trabajador.png"))); // NOI18N

        btnRegistrarEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/anotar.png"))); // NOI18N
        btnRegistrarEntrada.setText("REGISTRAR ENTRADA");
        btnRegistrarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEntradaActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/cerrarsesion.png"))); // NOI18N
        btnSalir.setText("CERRAR SESION");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnRecibo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/descargar.png"))); // NOI18N
        btnRecibo.setText("REPORTE ASISTENCIA");
        btnRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReciboActionPerformed(evt);
            }
        });

        btnRegistrarSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/anotar.png"))); // NOI18N
        btnRegistrarSalida.setText("REGISTRAR SALIDA");
        btnRegistrarSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarSalidaActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/logohd.jpg"))); // NOI18N

        tblAsistencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAsistencia.setEnabled(false);
        jScrollPane2.setViewportView(tblAsistencia);

        btnHonorario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/descargar.png"))); // NOI18N
        btnHonorario.setText("RECIBO POR HONORARIOS");
        btnHonorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHonorarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblBienvenida))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblPNG)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRecibo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHonorario, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(btnRegistrarSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistrarEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBienvenida)
                        .addGap(18, 18, 18)
                        .addComponent(lblPNG))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnRegistrarEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegistrarSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHonorario, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2)))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(819, 796));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEntradaActionPerformed
        String estado = obtenerUltimoEstado();

        if (estado.equals("ENTRADA")) {
            JOptionPane.showMessageDialog(this,
                    "Ya tienes una entrada registrada.\nDebes marcar SALIDA antes de entrar nuevamente.",
                    "Acción Bloqueada", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (JOptionPane.showConfirmDialog(this, "¿Marcar ENTRADA ahora?", "Registrar Entrada", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            sistema.registrarAsistencia(usuarioLogueado, "ENTRADA");
            sistema.guardarDatos();

            cargarHistorialAsistencia();

            JOptionPane.showMessageDialog(this,
                    "Entrada registrada con éxito.",
                    "Registro Exitoso",
                    JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btnRegistrarEntradaActionPerformed

    private void btnReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReciboActionPerformed
        try {

            File carpeta = new File("Trabajadores");
            if (!carpeta.exists()) {
                carpeta.mkdir();
            }

            String nombreArchivo = "Constancia_Trabajo_" + usuarioLogueado.getDni() + ".pdf";
            File archivoFinal = new File(carpeta, nombreArchivo);

            sistema.generarPDFAsistenciaPersonal(usuarioLogueado, archivoFinal.getAbsolutePath());

            JOptionPane.showMessageDialog(this, "Comprobante guardado en la carpeta 'Trabajadores'.");

            if (Desktop.isDesktopSupported() && archivoFinal.exists()) {
                Desktop.getDesktop().open(archivoFinal);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al generar PDF: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnReciboActionPerformed

    private void btnRegistrarSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarSalidaActionPerformed
        String estado = obtenerUltimoEstado();

        if (!estado.equals("ENTRADA")) {
            JOptionPane.showMessageDialog(this,
                    "No tienes una entrada activa.\nDebes marcar ENTRADA primero.",
                    "Acción Bloqueada", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (JOptionPane.showConfirmDialog(this, "¿Marcar SALIDA ahora?", "Registrar Salida", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            sistema.registrarAsistencia(usuarioLogueado, "SALIDA");
            sistema.guardarDatos();

            cargarHistorialAsistencia();

            JOptionPane.showMessageDialog(this,
                    "Salida registrada. ¡Buen descanso!",
                    "Registro Exitoso",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarSalidaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnHonorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHonorarioActionPerformed
        try {
            File carpeta = new File("Trabajadores");
            if (!carpeta.exists()) {
                carpeta.mkdir();
            }
            String nombreArchivo = "Recibo_Honorarios_" + usuarioLogueado.getDni() + ".pdf";
            File archivoFinal = new File(carpeta, nombreArchivo);

            sistema.generarPDFReciboHonorarios(usuarioLogueado, archivoFinal.getAbsolutePath());

            JOptionPane.showMessageDialog(this, "Recibo por Honorarios guardado en la carpeta 'Trabajadores'.");

            if (Desktop.isDesktopSupported() && archivoFinal.exists()) {
                Desktop.getDesktop().open(archivoFinal);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error PDF: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnHonorarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTrabajador.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTrabajador.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTrabajador.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTrabajador.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTrabajador().setVisible(true);
            }
        });
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("media/logofinal.png"));

        return retValue;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHonorario;
    private javax.swing.JButton btnRecibo;
    private javax.swing.JButton btnRegistrarEntrada;
    private javax.swing.JButton btnRegistrarSalida;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblPNG;
    private javax.swing.JTable tblAsistencia;
    // End of variables declaration//GEN-END:variables
}
